/**
 * Ambient type declarations for virtual modules generated by auwla/vite-router.
 *
 * These are global declarations (not an augmentation of an existing module)
 * so TypeScript understands imports like `import routes from 'auwla:routes'`
 * without any manual setup in the consumer project.
 */

declare module 'auwla:routes' {
  import type { Route } from 'auwla/router'
  const routes: Route[]
  export default routes
}

declare module 'auwla:islands' {
  const islands: unknown[]
  export default islands
}

declare module 'auwla:server-manifest' {
  import type { ServerManifest } from 'auwla/server'
  const manifest: ServerManifest
  export default manifest
}

declare module '*/server-manifest.js' {
  import type { ServerManifest } from 'auwla/server'
  const manifest: ServerManifest
  export default manifest
}
