/**
 * @fileoverview Code generators for the auwla/vite-router plugin.
 *
 * Two generators, each with a single responsibility:
 *
 *   generateVirtualModule() — static imports, all pages bundled together.
 *   Suitable for small apps or when bundle splitting is not needed.
 *
 *   generateLazyVirtualModule() — mixed strategy:
 *     - Pages WITH `routed` → dynamic import (code split per page).
 *       The chunk loads as the first step of routed so the component is
 *       guaranteed to be in memory by the time it renders.
 *     - Pages WITHOUT `routed` → static import (synchronous, zero overhead).
 *
 *   generateTypeFile() — produces `auwla.gen.ts`, a TypeScript declaration
 *   file that augments the `Register` interface in 'auwla/router'. This is
 *   what enables type-safe navigate(), isActive(), and <Link href>.
 *
 * All functions are pure (no I/O) and can be unit-tested independently
 * of any Vite infrastructure.
 */

import type { PageFile } from './types'

// ---------------------------------------------------------------------------
// Virtual module
// ---------------------------------------------------------------------------

/**
 * Generates the source code for the `auwla:routes` virtual module.
 *
 * The output is a module that:
 *   - Imports every discovered page file with a stable `pageN` alias.
 *   - Builds and exports a route table via `defineRoutes([...])`.
 *   - Includes only the optional route properties (routed, pendingComponent,
 *     errorComponent, guard, meta) when the corresponding export exists in
 *     the page file — keeping each route object minimal.
 *
 * Example output for two pages:
 *
 *   import { defineRoutes } from 'auwla/router'
 *   import * as page0 from '/abs/src/pages/index.tsx'
 *   import * as page1 from '/abs/src/pages/posts/[id].tsx'
 *
 *   export default defineRoutes([
 *     { path: '/', component: page0.default },
 *     {
 *       path: '/posts/:id',
 *       component: page1.default,
 *       routed: page1.routed,
 *       pendingComponent: page1.pending,
 *     },
 *   ])
 */
export function generateVirtualModule(pages: PageFile[]): string {
  const lines: string[] = [
    '// auwla:routes — auto-generated by auwla/vite-router',
    '// Do not edit. Re-generated whenever the pages directory changes.',
    '',
    "import { defineRoutes } from 'auwla/router'",
  ]

  // One static import per page. Absolute paths ensure Vite resolves them
  // regardless of which directory the virtual module is "located" in.
  for (const [i, page] of pages.entries()) {
    // Use POSIX-style paths for cross-platform Vite compatibility.
    const importPath = page.filePath.replace(/\\/g, '/')
    lines.push(`import * as page${i} from ${JSON.stringify(importPath)}`)
  }

  lines.push('')
  lines.push('export default defineRoutes([')

  for (const [i, page] of pages.entries()) {
    const alias = `page${i}`
    const { exports: ex } = page

    // Build the list of non-empty route properties.
    const props: string[] = [
      `    path: ${JSON.stringify(page.routePath)}`,
      `    component: ${alias}.default`,
    ]

    // Optional route properties — only emitted when the export exists.
    if (ex.hasRouted)  props.push(`    routed: ${alias}.routed`)
    if (ex.hasPending) props.push(`    pendingComponent: ${alias}.pending`)
    if (ex.hasError)   props.push(`    errorComponent: ${alias}.error`)
    if (ex.hasGuard)   props.push(`    guard: ${alias}.guard`)
    if (ex.hasMeta)    props.push(`    meta: ${alias}.meta`)

    lines.push(`  {`)
    lines.push(props.join(',\n'))
    lines.push(`  },`)
  }

  lines.push('])')
  lines.push('')

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Lazy virtual module (code splitting)
// ---------------------------------------------------------------------------

/**
 * Generates the source code for the `auwla:routes` virtual module with
 * per-page code splitting via dynamic imports.
 *
 * Strategy:
 *   - Pages WITH `routed` → dynamic import.
 *     The chunk is fetched as the first await inside the generated routed
 *     wrapper, so by the time the component renders the module is cached.
 *   - Pages WITHOUT `routed` → static import (eager, zero async overhead).
 *
 * The `__mods` Map and `__load` helper are inlined in the virtual module
 * so it has zero runtime dependencies beyond 'auwla/router'.
 *
 * Guard / meta on lazy pages are read from the module cache at call time.
 * On the very first navigation to a lazy page they are undefined (module
 * not yet loaded). They work correctly on all subsequent visits once the
 * module is cached. Document this in your app if you rely on guards.
 *
 * Example output (simplified):
 *
 *   import { defineRoutes } from 'auwla/router'
 *   import * as sp0 from '/src/pages/index.tsx'  // static (no routed)
 *
 *   const __mods = new Map()
 *   function __load(key, fn) { ... }
 *
 *   export default defineRoutes([
 *     { path: '/', component: sp0.default },
 *     {
 *       path: '/posts/:id',
 *       component: (p) => __mods.get('/posts/:id')?.default?.(p) ?? (() => null),
 *       routed: async (ctx, signal) => {
 *         const mod = await __load('/posts/:id', () => import('/src/pages/posts/[id].tsx'))
 *         return mod.routed(ctx, signal)
 *       },
 *     },
 *   ])
 *
 *   export const __prefetch = {
 *     '/posts/:id': () => __load('/posts/:id', () => import('/src/pages/posts/[id].tsx')),
 *   }
 */
export function generateLazyVirtualModule(pages: PageFile[]): string {
  // Split into static (no routed) and lazy (has routed).
  const staticPages = pages.filter((p) => !p.exports.hasRouted)
  const lazyPages   = pages.filter((p) =>  p.exports.hasRouted)

  const lines: string[] = [
    '// auwla:routes — auto-generated by auwla/vite-router',
    '// Do not edit. Re-generated whenever the pages directory changes.',
    '',
    "import { defineRoutes } from 'auwla/router'",
  ]

  // Static imports for pages without routed.
  for (const [i, page] of staticPages.entries()) {
    const importPath = page.filePath.replace(/\\/g, '/')
    lines.push(`import * as sp${i} from ${JSON.stringify(importPath)}`)
  }

  // Inline the module cache + loader helper only when there are lazy pages.
  if (lazyPages.length > 0) {
    lines.push('')
    lines.push('/** Module cache — populated as lazy pages are visited for the first time. */')
    lines.push('const __mods = new Map()')
    lines.push('')
    lines.push('/**')
    lines.push(' * Loads a page chunk once and caches it.')
    lines.push(' * Concurrent calls for the same key share a single in-flight promise.')
    lines.push(' */')
    lines.push('const __inflight = new Map()')
    lines.push('function __load(key, importFn) {')
    lines.push('  if (__mods.has(key)) return Promise.resolve(__mods.get(key))')
    lines.push('  if (__inflight.has(key)) return __inflight.get(key)')
    lines.push('  const p = importFn().then(mod => { __mods.set(key, mod); __inflight.delete(key); return mod })')
    lines.push('  __inflight.set(key, p)')
    lines.push('  return p')
    lines.push('}')
  }

  lines.push('')
  lines.push('export default defineRoutes([')

  // Static routes.
  for (const [i, page] of staticPages.entries()) {
    const alias = `sp${i}`
    const props: string[] = [
      `    path: ${JSON.stringify(page.routePath)}`,
      `    component: ${alias}.default`,
    ]
    if (page.exports.hasPending) props.push(`    pendingComponent: ${alias}.pending`)
    if (page.exports.hasError)   props.push(`    errorComponent: ${alias}.error`)
    if (page.exports.hasGuard)   props.push(`    guard: ${alias}.guard`)
    if (page.exports.hasMeta)    props.push(`    meta: ${alias}.meta`)
    lines.push('  {')
    lines.push(props.join(',\n'))
    lines.push('  },')
  }

  // Lazy routes (have routed → use dynamic import).
  for (const page of lazyPages) {
    const key        = JSON.stringify(page.routePath)
    const importPath = JSON.stringify(page.filePath.replace(/\\/g, '/'))
    const { exports: ex } = page

    lines.push('  {')
    lines.push(`    path: ${key},`)

    // Component reads from the module cache.
    // By the time this renders, routed has already awaited __load(), so
    // __mods.get(key) is guaranteed to be populated.
    lines.push(`    component: (props) => __mods.get(${key})?.default?.(props) ?? (() => null),`)

    // Routed: load chunk first, then delegate to the real routed function.
    lines.push(`    routed: async (ctx, signal) => {`)
    lines.push(`      const mod = await __load(${key}, () => import(${importPath}))`)
    lines.push(`      return mod.routed(ctx, signal)`)
    lines.push(`    },`)

    // Optional properties — all read lazily from the module cache.
    if (ex.hasPending) {
      lines.push(`    pendingComponent: () => __mods.get(${key})?.pending?.() ?? null,`)
    }
    if (ex.hasError) {
      lines.push(`    errorComponent: (props) => {`)
      lines.push(`      const mod = __mods.get(${key})`)
      lines.push(`      return mod?.error ? mod.error(props) : () => null`)
      lines.push(`    },`)
    }
    if (ex.hasGuard) {
      // Guard is read from cache. On first navigation guard is undefined
      // (module not yet loaded). Document this limitation.
      lines.push(`    guard: (ctx) => __mods.get(${key})?.guard?.(ctx),`)
    }
    if (ex.hasMeta) {
      // Meta is a getter so it reads the live cache value on each access.
      lines.push(`    get meta() { return __mods.get(${key})?.meta },`)
    }

    lines.push('  },')
  }

  lines.push('])')
  lines.push('')

  // Export a __prefetch map so Link can pre-warm chunks on hover.
  // The key is the route path; the value is a zero-argument function that
  // triggers the dynamic import (idempotent — uses the same __load cache).
  if (lazyPages.length > 0) {
    lines.push('/**')
    lines.push(' * Prefetch map — used by <Link prefetch> to start chunk downloads')
    lines.push(' * and routed data on mouseenter before the user clicks.')
    lines.push(' * Import and pass to registerPrefetches() in your app entry.')
    lines.push(' */')
    lines.push('export const __prefetch = {')
    for (const page of lazyPages) {
      const key        = JSON.stringify(page.routePath)
      const importPath = JSON.stringify(page.filePath.replace(/\\/g, '/'))
      lines.push(`  [${key}]: () => __load(${key}, () => import(${importPath})),`)
    }
    lines.push('}')
    lines.push('')
  }

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Type augmentation file
// ---------------------------------------------------------------------------

/**
 * Generates the content of `auwla.gen.ts`.
 *
 * The file performs a TypeScript module augmentation on 'auwla/router',
 * declaring the discovered route paths inside the `Register` interface.
 * Once TypeScript sees this file, the following all become path-validated:
 *
 *   navigate('/posts/:id', { id: '3' })  // ✅ typed params
 *   navigate('/not-found')               // ❌ compile error
 *   isActive('/posts')                   // ✅ valid path
 *   <Link href="/unknown" />             // ❌ compile error
 *
 * The generated file must be committed to version control so that CI and
 * editor type-checking work without running the Vite dev server first.
 *
 * Example output for three pages:
 *
 *   declare module 'auwla/router' {
 *     interface Register {
 *       routes: [
 *         { path: '/' },
 *         { path: '/posts' },
 *         { path: '/posts/:id' },
 *       ]
 *     }
 *   }
 *   export {}
 */
export function generateTypeFile(pages: PageFile[]): string {
  const routeEntries = pages
    .map((p) => `      { path: ${JSON.stringify(p.routePath)} }`)
    .join(',\n')

  return [
    '// auwla.gen.ts — auto-generated by auwla/vite-router',
    '// Do not edit this file directly.',
    '//',
    '// Augments the Register interface in auwla/router to enable type-safe',
    '// navigation. Commit this file so CI type-checking works without running',
    '// the Vite dev server.',
    '',
    "declare module 'auwla/router' {",
    '  interface Register {',
    '    routes: [',
    routeEntries,
    '    ]',
    '  }',
    '}',
    '',
    '// Needed to make this a module rather than a global script.',
    'export {}',
    '',
  ].join('\n')
}
