/**
 * @fileoverview Code generators for the auwla/vite-router plugin.
 *
 * Two generators, each with a single responsibility:
 *
 *   generateVirtualModule() — produces the source of the `auwla:routes`
 *   virtual module that the app imports. It creates a static-import route
 *   table using defineRoutes(), wiring only the exports that exist in each
 *   page file.
 *
 *   generateTypeFile() — produces `auwla.gen.ts`, a TypeScript declaration
 *   file that augments the `Register` interface in 'auwla/router'. This is
 *   what enables type-safe navigate(), isActive(), and <Link href>.
 *
 * Both functions are pure (no I/O) and can be unit-tested independently
 * of any Vite infrastructure.
 */

import type { PageFile } from './types'

// ---------------------------------------------------------------------------
// Virtual module
// ---------------------------------------------------------------------------

/**
 * Generates the source code for the `auwla:routes` virtual module.
 *
 * The output is a module that:
 *   - Imports every discovered page file with a stable `pageN` alias.
 *   - Builds and exports a route table via `defineRoutes([...])`.
 *   - Includes only the optional route properties (routed, pendingComponent,
 *     errorComponent, guard, meta) when the corresponding export exists in
 *     the page file — keeping each route object minimal.
 *
 * Example output for two pages:
 *
 *   import { defineRoutes } from 'auwla/router'
 *   import * as page0 from '/abs/src/pages/index.tsx'
 *   import * as page1 from '/abs/src/pages/posts/[id].tsx'
 *
 *   export default defineRoutes([
 *     { path: '/', component: page0.default },
 *     {
 *       path: '/posts/:id',
 *       component: page1.default,
 *       routed: page1.routed,
 *       pendingComponent: page1.pending,
 *     },
 *   ])
 */
export function generateVirtualModule(pages: PageFile[]): string {
  const lines: string[] = [
    '// auwla:routes — auto-generated by auwla/vite-router',
    '// Do not edit. Re-generated whenever the pages directory changes.',
    '',
    "import { defineRoutes } from 'auwla/router'",
  ]

  // One static import per page. Absolute paths ensure Vite resolves them
  // regardless of which directory the virtual module is "located" in.
  for (const [i, page] of pages.entries()) {
    // Use POSIX-style paths for cross-platform Vite compatibility.
    const importPath = page.filePath.replace(/\\/g, '/')
    lines.push(`import * as page${i} from ${JSON.stringify(importPath)}`)
  }

  lines.push('')
  lines.push('export default defineRoutes([')

  for (const [i, page] of pages.entries()) {
    const alias = `page${i}`
    const { exports: ex } = page

    // Build the list of non-empty route properties.
    const props: string[] = [
      `    path: ${JSON.stringify(page.routePath)}`,
      `    component: ${alias}.default`,
    ]

    // Optional route properties — only emitted when the export exists.
    if (ex.hasRouted)  props.push(`    routed: ${alias}.routed`)
    if (ex.hasPending) props.push(`    pendingComponent: ${alias}.pending`)
    if (ex.hasError)   props.push(`    errorComponent: ${alias}.error`)
    if (ex.hasGuard)   props.push(`    guard: ${alias}.guard`)
    if (ex.hasMeta)    props.push(`    meta: ${alias}.meta`)

    lines.push(`  {`)
    lines.push(props.join(',\n'))
    lines.push(`  },`)
  }

  lines.push('])')
  lines.push('')

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Type augmentation file
// ---------------------------------------------------------------------------

/**
 * Generates the content of `auwla.gen.ts`.
 *
 * The file performs a TypeScript module augmentation on 'auwla/router',
 * declaring the discovered route paths inside the `Register` interface.
 * Once TypeScript sees this file, the following all become path-validated:
 *
 *   navigate('/posts/:id', { id: '3' })  // ✅ typed params
 *   navigate('/not-found')               // ❌ compile error
 *   isActive('/posts')                   // ✅ valid path
 *   <Link href="/unknown" />             // ❌ compile error
 *
 * The generated file must be committed to version control so that CI and
 * editor type-checking work without running the Vite dev server first.
 *
 * Example output for three pages:
 *
 *   declare module 'auwla/router' {
 *     interface Register {
 *       routes: [
 *         { path: '/' },
 *         { path: '/posts' },
 *         { path: '/posts/:id' },
 *       ]
 *     }
 *   }
 *   export {}
 */
export function generateTypeFile(pages: PageFile[]): string {
  const routeEntries = pages
    .map((p) => `      { path: ${JSON.stringify(p.routePath)} }`)
    .join(',\n')

  return [
    '// auwla.gen.ts — auto-generated by auwla/vite-router',
    '// Do not edit this file directly.',
    '//',
    '// Augments the Register interface in auwla/router to enable type-safe',
    '// navigation. Commit this file so CI type-checking works without running',
    '// the Vite dev server.',
    '',
    "declare module 'auwla/router' {",
    '  interface Register {',
    '    routes: [',
    routeEntries,
    '    ]',
    '  }',
    '}',
    '',
    '// Needed to make this a module rather than a global script.',
    'export {}',
    '',
  ].join('\n')
}
