/**
 * @fileoverview Code generators for the auwla/vite-router plugin.
 *
 * Two generators, each with a single responsibility:
 *
 *   generateVirtualModule() — static imports, all pages bundled together.
 *   Suitable for small apps or when bundle splitting is not needed.
 *
 *   generateLazyVirtualModule() — mixed strategy:
 *     - Pages WITH `routed` → dynamic import (code split per page).
 *       The chunk loads as the first step of routed so the component is
 *       guaranteed to be in memory by the time it renders.
 *     - Pages WITHOUT `routed` → static import (synchronous, zero overhead).
 *
 *   generateTypeFile() — produces `auwla.gen.ts`, a TypeScript declaration
 *   file that augments the `Register` interface in 'auwla/router'. This is
 *   what enables type-safe navigate(), isActive(), and <Link href>.
 *
 * All functions are pure (no I/O) and can be unit-tested independently
 * of any Vite infrastructure.
 */

import type { PageFile, DirectoryNode, LayoutFile } from './types'
import { posixDirname } from './scanner'

// ---------------------------------------------------------------------------
// Virtual module
// ---------------------------------------------------------------------------

/**
 * Generates the source code for the `auwla:routes` virtual module.
 *
 * The output is a module that:
 *   - Imports every discovered page file with a stable `pageN` alias.
 *   - Builds and exports a route table via `defineRoutes([...])`.
 *   - Includes only the optional route properties (routed, pendingComponent,
 *     errorComponent, guard, meta) when the corresponding export exists in
 *     the page file — keeping each route object minimal.
 *
 * Example output for two pages:
 *
 *   import { defineRoutes } from 'auwla/router'
 *   import * as page0 from '/abs/src/pages/index.tsx'
 *   import * as page1 from '/abs/src/pages/posts/[id].tsx'
 *
 *   export default defineRoutes([
 *     { path: '/', component: page0.default },
 *     {
 *       path: '/posts/:id',
 *       component: page1.default,
 *       routed: page1.routed,
 *       pendingComponent: page1.pending,
 *     },
 *   ])
 */
export function generateVirtualModule(pages: PageFile[]): string {
  const lines: string[] = [
    '// auwla:routes — auto-generated by auwla/vite-router',
    '// Do not edit. Re-generated whenever the pages directory changes.',
    '',
    "import { defineRoutes } from 'auwla/router'",
  ]

  // One static import per page. Absolute paths ensure Vite resolves them
  // regardless of which directory the virtual module is "located" in.
  for (const [i, page] of pages.entries()) {
    // Use POSIX-style paths for cross-platform Vite compatibility.
    const importPath = page.filePath.replace(/\\/g, '/')
    lines.push(`import * as page${i} from ${JSON.stringify(importPath)}`)
  }

  lines.push('')
  lines.push('export default defineRoutes([')

  for (const [i, page] of pages.entries()) {
    const alias = `page${i}`
    const { exports: ex } = page

    // Build the list of non-empty route properties.
    const props: string[] = [
      `    path: ${JSON.stringify(page.routePath)}`,
      `    component: ${alias}.default`,
    ]

    // Optional route properties — only emitted when the export exists.
    if (ex.hasRouted)  props.push(`    routed: ${alias}.routed`)
    if (ex.hasPending) props.push(`    pendingComponent: ${alias}.pending`)
    if (ex.hasError)   props.push(`    errorComponent: ${alias}.error`)
    if (ex.hasGuard)   props.push(`    guard: ${alias}.guard`)
    if (ex.hasMeta)    props.push(`    meta: ${alias}.meta`)

    lines.push(`  {`)
    lines.push(props.join(',\n'))
    lines.push(`  },`)
  }

  lines.push('])')
  lines.push('')

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Lazy virtual module (code splitting)
// ---------------------------------------------------------------------------

/**
 * Generates the source code for the `auwla:routes` virtual module with
 * per-page code splitting via dynamic imports.
 *
 * Strategy:
 *   - Pages WITH `routed` → dynamic import.
 *     The chunk is fetched as the first await inside the generated routed
 *     wrapper, so by the time the component renders the module is cached.
 *   - Pages WITHOUT `routed` → static import (eager, zero async overhead).
 *
 * The `__mods` Map and `__load` helper are inlined in the virtual module
 * so it has zero runtime dependencies beyond 'auwla/router'.
 *
 * Guard / meta on lazy pages are read from the module cache at call time.
 * On the very first navigation to a lazy page they are undefined (module
 * not yet loaded). They work correctly on all subsequent visits once the
 * module is cached. Document this in your app if you rely on guards.
 *
 * Example output (simplified):
 *
 *   import { defineRoutes } from 'auwla/router'
 *   import * as sp0 from '/src/pages/index.tsx'  // static (no routed)
 *
 *   const __mods = new Map()
 *   function __load(key, fn) { ... }
 *
 *   export default defineRoutes([
 *     { path: '/', component: sp0.default },
 *     {
 *       path: '/posts/:id',
 *       component: (p) => __mods.get('/posts/:id')?.default?.(p) ?? (() => null),
 *       routed: async (ctx, signal) => {
 *         const mod = await __load('/posts/:id', () => import('/src/pages/posts/[id].tsx'))
 *         return mod.routed(ctx, signal)
 *       },
 *     },
 *   ])
 *
 *   export const __prefetch = {
 *     '/posts/:id': () => __load('/posts/:id', () => import('/src/pages/posts/[id].tsx')),
 *   }
 */
export function generateLazyVirtualModule(pages: PageFile[]): string {
  // Split into static (no routed) and lazy (has routed).
  const staticPages = pages.filter((p) => !p.exports.hasRouted)
  const lazyPages   = pages.filter((p) =>  p.exports.hasRouted)

  const lines: string[] = [
    '// auwla:routes — auto-generated by auwla/vite-router',
    '// Do not edit. Re-generated whenever the pages directory changes.',
    '',
    "import { defineRoutes } from 'auwla/router'",
  ]

  // Static imports for pages without routed.
  for (const [i, page] of staticPages.entries()) {
    const importPath = page.filePath.replace(/\\/g, '/')
    lines.push(`import * as sp${i} from ${JSON.stringify(importPath)}`)
  }

  // Inline the module cache + loader helper only when there are lazy pages.
  if (lazyPages.length > 0) {
    lines.push('')
    lines.push('/** Module cache — populated as lazy pages are visited for the first time. */')
    lines.push('const __mods = new Map()')
    lines.push('')
    lines.push('/**')
    lines.push(' * Loads a page chunk once and caches it.')
    lines.push(' * Concurrent calls for the same key share a single in-flight promise.')
    lines.push(' */')
    lines.push('const __inflight = new Map()')
    lines.push('function __load(key, importFn) {')
    lines.push('  if (__mods.has(key)) return Promise.resolve(__mods.get(key))')
    lines.push('  if (__inflight.has(key)) return __inflight.get(key)')
    lines.push('  const p = importFn().then(mod => { __mods.set(key, mod); __inflight.delete(key); return mod })')
    lines.push('  __inflight.set(key, p)')
    lines.push('  return p')
    lines.push('}')
  }

  lines.push('')
  lines.push('export default defineRoutes([')

  // Static routes.
  for (const [i, page] of staticPages.entries()) {
    const alias = `sp${i}`
    const props: string[] = [
      `    path: ${JSON.stringify(page.routePath)}`,
      `    component: ${alias}.default`,
    ]
    if (page.exports.hasPending) props.push(`    pendingComponent: ${alias}.pending`)
    if (page.exports.hasError)   props.push(`    errorComponent: ${alias}.error`)
    if (page.exports.hasGuard)   props.push(`    guard: ${alias}.guard`)
    if (page.exports.hasMeta)    props.push(`    meta: ${alias}.meta`)
    lines.push('  {')
    lines.push(props.join(',\n'))
    lines.push('  },')
  }

  // Lazy routes (have routed → use dynamic import).
  for (const page of lazyPages) {
    const key        = JSON.stringify(page.routePath)
    const importPath = JSON.stringify(page.filePath.replace(/\\/g, '/'))
    const { exports: ex } = page

    lines.push('  {')
    lines.push(`    path: ${key},`)

    // Component reads from the module cache.
    // By the time this renders, routed has already awaited __load(), so
    // __mods.get(key) is guaranteed to be populated.
    lines.push(`    component: (props) => __mods.get(${key})?.default?.(props) ?? (() => null),`)

    // Routed: load chunk first, then delegate to the real routed function.
    lines.push(`    routed: async (ctx, signal) => {`)
    lines.push(`      const mod = await __load(${key}, () => import(${importPath}))`)
    lines.push(`      return mod.routed(ctx, signal)`)
    lines.push(`    },`)

    // Optional properties — all read lazily from the module cache.
    if (ex.hasPending) {
      lines.push(`    pendingComponent: () => __mods.get(${key})?.pending?.() ?? null,`)
    }
    if (ex.hasError) {
      lines.push(`    errorComponent: (props) => {`)
      lines.push(`      const mod = __mods.get(${key})`)
      lines.push(`      return mod?.error ? mod.error(props) : () => null`)
      lines.push(`    },`)
    }
    if (ex.hasGuard) {
      // Guard is read from cache. On first navigation guard is undefined
      // (module not yet loaded). Document this limitation.
      lines.push(`    guard: (ctx) => __mods.get(${key})?.guard?.(ctx),`)
    }
    if (ex.hasMeta) {
      // Meta is a getter so it reads the live cache value on each access.
      lines.push(`    get meta() { return __mods.get(${key})?.meta },`)
    }

    lines.push('  },')
  }

  lines.push('])')
  lines.push('')

  // Export a __prefetch map so Link can pre-warm chunks on hover.
  // The key is the route path; the value is a zero-argument function that
  // triggers the dynamic import (idempotent — uses the same __load cache).
  if (lazyPages.length > 0) {
    lines.push('/**')
    lines.push(' * Prefetch map — used by <Link prefetch> to start chunk downloads')
    lines.push(' * and routed data on mouseenter before the user clicks.')
    lines.push(' * Import and pass to registerPrefetches() in your app entry.')
    lines.push(' */')
    lines.push('export const __prefetch = {')
    for (const page of lazyPages) {
      const key        = JSON.stringify(page.routePath)
      const importPath = JSON.stringify(page.filePath.replace(/\\/g, '/'))
      lines.push(`  [${key}]: () => __load(${key}, () => import(${importPath})),`)
    }
    lines.push('}')
    lines.push('')
  }

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Layout-aware virtual module
// ---------------------------------------------------------------------------

/**
 * Generates the `auwla:routes` virtual module with full layout support.
 *
 * Reads the directory tree built by `buildDirectoryTree()` and generates a
 * FLAT route list where each page's `component` is pre-wrapped with its
 * layout chain — outermost layout applied last (wraps the most).
 *
 * Why flat routes instead of nested `group()` calls?
 * `group(base, ...)` calls `flattenRoutes(routes, base)` internally, which
 * prepends `base` to each route's path. Nesting two `group()` calls would
 * cause double-prefixing for non-root outer groups. Generating flat routes
 * with explicit layout chains avoids that entirely.
 *
 * Layout chain for `src/pages/dashboard/users.tsx` when both
 * `_layout.tsx` (root) and `dashboard/_layout.tsx` exist:
 *   component = () => lay0.default(() => lay1.default(page0.default))
 *   Where lay0 = root layout (outermost), lay1 = dashboard layout (inner).
 *
 * Guard from a layout file (`export const guard`) is applied to every page
 * in that directory. If a page also has its own guard, the layout guard
 * wraps it: page guard runs first, layout guard runs if page guard passes.
 *
 * The `lazy` flag follows the same strategy as `generateLazyVirtualModule`:
 * pages WITH `routed` get dynamic imports, pages WITHOUT stay static.
 *
 * Example output for two pages, root layout + dashboard layout:
 *
 *   import { defineRoutes } from 'auwla/router'
 *   import * as lay0 from '/src/pages/_layout.tsx'
 *   import * as lay1 from '/src/pages/dashboard/_layout.tsx'
 *   import * as page0 from '/src/pages/index.tsx'
 *   import * as page1 from '/src/pages/dashboard/index.tsx'
 *
 *   export default defineRoutes([
 *     {
 *       path: '/',
 *       component: () => lay0.default(page0.default),
 *     },
 *     {
 *       path: '/dashboard',
 *       component: () => lay0.default(() => lay1.default(page1.default)),
 *     },
 *   ])
 */
export function generateVirtualModuleWithLayouts(
  tree: DirectoryNode,
  lazy = false,
): string {
  // -----------------------------------------------------------------------
  // 1. Collect all pages and layouts from the tree (depth-first, root first)
  // -----------------------------------------------------------------------

  const allLayouts = collectLayouts(tree)  // parent-before-child order
  const allPages   = collectPages(tree)    // same visit order as tree traversal

  // -----------------------------------------------------------------------
  // 2. Assign import aliases
  // -----------------------------------------------------------------------

  /** filePath → alias for layout imports (always static) */
  const layoutAlias = new Map<string, string>()
  let idx = 0
  for (const layout of allLayouts) {
    layoutAlias.set(layout.filePath, `lay${idx++}`)
  }

  /** filePath → alias for static page imports (when !lazy or no routed) */
  const pageAlias = new Map<string, string>()
  for (const page of allPages) {
    if (!lazy || !page.exports.hasRouted) {
      pageAlias.set(page.filePath, `page${idx++}`)
    }
  }

  // -----------------------------------------------------------------------
  // 3. Emit header + imports
  // -----------------------------------------------------------------------

  const lines: string[] = [
    '// auwla:routes — auto-generated by auwla/vite-router',
    '// Do not edit. Re-generated whenever the pages directory changes.',
    '',
    "import { defineRoutes } from 'auwla/router'",
  ]

  // Layout imports (always static — layouts must be synchronously available)
  for (const layout of allLayouts) {
    const alias = layoutAlias.get(layout.filePath)!
    const path  = layout.filePath.replace(/\\/g, '/')
    lines.push(`import * as ${alias} from ${JSON.stringify(path)}`)
  }

  // Static page imports
  for (const page of allPages) {
    const alias = pageAlias.get(page.filePath)
    if (alias) {
      const path = page.filePath.replace(/\\/g, '/')
      lines.push(`import * as ${alias} from ${JSON.stringify(path)}`)
    }
  }

  // Lazy infrastructure when needed
  const lazyPages = allPages.filter((p) => lazy && p.exports.hasRouted)
  if (lazyPages.length > 0) {
    lines.push('')
    lines.push('const __mods = new Map()')
    lines.push('const __inflight = new Map()')
    lines.push('function __load(key, importFn) {')
    lines.push('  if (__mods.has(key)) return Promise.resolve(__mods.get(key))')
    lines.push('  if (__inflight.has(key)) return __inflight.get(key)')
    lines.push('  const p = importFn().then(mod => { __mods.set(key, mod); __inflight.delete(key); return mod })')
    lines.push('  __inflight.set(key, p)')
    lines.push('  return p')
    lines.push('}')
  }

  // -----------------------------------------------------------------------
  // 4. Emit defineRoutes([...])
  // -----------------------------------------------------------------------

  lines.push('')
  lines.push('export default defineRoutes([')

  for (const page of allPages) {
    const chain = getLayoutChain(page, tree)                // [outerLayout, ..., innerLayout]
    const aliasChain = chain.map((l) => layoutAlias.get(l.filePath)!)

    const alias = pageAlias.get(page.filePath)
    const { exports: ex } = page

    lines.push('  {')
    lines.push(`    path: ${JSON.stringify(page.routePath)},`)

    if (alias) {
      // Static page
      const componentExpr = buildComponentExpr(`${alias}.default`, aliasChain)
      lines.push(`    component: ${componentExpr},`)

      if (ex.hasRouted)  lines.push(`    routed: ${alias}.routed,`)
      if (ex.hasPending) lines.push(`    pendingComponent: ${alias}.pending,`)
      if (ex.hasError)   lines.push(`    errorComponent: ${alias}.error,`)
      if (ex.hasGuard)   lines.push(`    guard: ${buildGuardExpr(`${alias}.guard`, chain, layoutAlias)},`)
      else if (chain.some((l) => l.hasGuard)) {
        // No page guard, but layout(s) have guards — apply layout chain guards.
        lines.push(`    guard: ${buildLayoutGuardOnly(chain, layoutAlias)},`)
      }
      if (ex.hasMeta)    lines.push(`    meta: ${alias}.meta,`)
    } else {
      // Lazy page (dynamic import)
      const key        = JSON.stringify(page.routePath)
      const importPath = JSON.stringify(page.filePath.replace(/\\/g, '/'))
      const cacheExpr  = `(props) => __mods.get(${key})?.default?.(props) ?? (() => null)`
      const componentExpr = buildComponentExpr(cacheExpr, aliasChain)
      lines.push(`    component: ${componentExpr},`)

      lines.push(`    routed: async (ctx, signal) => {`)
      lines.push(`      const mod = await __load(${key}, () => import(${importPath}))`)
      lines.push(`      return mod.routed(ctx, signal)`)
      lines.push(`    },`)

      if (ex.hasPending) lines.push(`    pendingComponent: () => __mods.get(${key})?.pending?.() ?? null,`)
      if (ex.hasError) {
        lines.push(`    errorComponent: (props) => {`)
        lines.push(`      const mod = __mods.get(${key})`)
        lines.push(`      return mod?.error ? mod.error(props) : () => null`)
        lines.push(`    },`)
      }
      if (ex.hasGuard)   lines.push(`    guard: (ctx) => __mods.get(${key})?.guard?.(ctx),`)
      if (ex.hasMeta)    lines.push(`    get meta() { return __mods.get(${key})?.meta },`)
    }

    lines.push('  },')
  }

  lines.push('])')
  lines.push('')

  // Prefetch map for lazy pages
  if (lazyPages.length > 0) {
    lines.push('export const __prefetch = {')
    for (const page of lazyPages) {
      const key        = JSON.stringify(page.routePath)
      const importPath = JSON.stringify(page.filePath.replace(/\\/g, '/'))
      lines.push(`  [${key}]: () => __load(${key}, () => import(${importPath})),`)
    }
    lines.push('}')
    lines.push('')
  }

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Layout codegen helpers
// ---------------------------------------------------------------------------

/**
 * Collects all layout files from the tree in depth-first, parent-before-child
 * order. This is the import order used in the generated module.
 */
function collectLayouts(node: DirectoryNode): LayoutFile[] {
  const result: LayoutFile[] = []
  if (node.layout) result.push(node.layout)
  for (const child of node.children) result.push(...collectLayouts(child))
  return result
}

/**
 * Collects all page files from the tree in depth-first order,
 * matching the sorted route order from `scanPages()`.
 */
function collectPages(node: DirectoryNode): PageFile[] {
  const result: PageFile[] = [...node.pages]
  for (const child of node.children) result.push(...collectPages(child))
  return result
}

/**
 * Returns the layout chain for a given page, ordered outermost first.
 *
 * The chain is built by walking from the root of the directory tree down to
 * the directory that contains the page, collecting any layout found at each
 * level.
 *
 * Example: page at 'dashboard/users.tsx' with root layout + dashboard layout
 *   → [rootLayout, dashboardLayout]
 *
 * The generated component expression wraps from inside out:
 *   () => rootLayout(() => dashboardLayout(page.default))
 */
function getLayoutChain(page: PageFile, tree: DirectoryNode): LayoutFile[] {
  const pageDirParts = posixDirname(page.relativePath)
    .split('/')
    .filter(Boolean)  // '' for root-level pages

  const chain: LayoutFile[] = []
  let node = tree

  if (node.layout) chain.push(node.layout)

  for (const part of pageDirParts) {
    const child = node.children.find(
      (c) => c.dirPath.split('/').at(-1) === part,
    )
    if (!child) break
    node = child
    if (node.layout) chain.push(node.layout)
  }

  return chain
}

/**
 * Builds a component expression string with the given layout chain applied.
 *
 * The base expression is wrapped from innermost to outermost:
 *   buildComponentExpr('page0.default', ['lay0', 'lay1'])
 *   → '() => lay0.default(() => lay1.default(page0.default))'
 *
 * With no layouts:
 *   buildComponentExpr('page0.default', []) → 'page0.default'
 */
function buildComponentExpr(baseExpr: string, layerAliases: string[]): string {
  if (layerAliases.length === 0) return baseExpr

  // Wrap from innermost to outermost (reverse the chain)
  let expr = baseExpr
  for (let i = layerAliases.length - 1; i >= 0; i--) {
    expr = `() => ${layerAliases[i]!}.default(${expr})`
  }
  return expr
}

/**
 * Builds a guard expression for a page that has its own guard AND may also
 * have layout guards.
 *
 * Execution order mirrors how nested `group()` calls chain guards:
 *   1. Page guard (most specific — runs first).
 *   2. Innermost layout guard.
 *   3. Outermost layout guard (least specific — runs last).
 *
 * The `chain` array is outermost-first, so we reverse it before iterating.
 * If any guard blocks (returns false / redirect string), later guards are skipped.
 */
function buildGuardExpr(
  pageGuardExpr: string,
  chain: LayoutFile[],
  layoutAlias: Map<string, string>,
): string {
  // Reverse: chain is [outerLayout, ..., innerLayout]; we need inner first.
  const layoutGuards = [...chain]
    .reverse()
    .filter((l) => l.hasGuard)
    .map((l) => `${layoutAlias.get(l.filePath)!}.guard`)

  if (layoutGuards.length === 0) return pageGuardExpr

  // Compose: page guard first, then each layout guard from inner to outer.
  // Returns the first non-passing result (truthy string = redirect, false = block).
  const allGuards = [pageGuardExpr, ...layoutGuards].join(', ')
  return `(ctx) => [${allGuards}].reduce((r, g) => r !== undefined && r !== true ? r : g(ctx), undefined)`
}

/**
 * Builds a guard expression for a page with no page-level guard but with
 * one or more layout guards.
 *
 * Same innermost-first ordering as buildGuardExpr (reversed from chain order).
 */
function buildLayoutGuardOnly(
  chain: LayoutFile[],
  layoutAlias: Map<string, string>,
): string {
  // Reverse: chain is [outerLayout, ..., innerLayout]; we need inner first.
  const guards = [...chain]
    .reverse()
    .filter((l) => l.hasGuard)
    .map((l) => `${layoutAlias.get(l.filePath)!}.guard`)

  if (guards.length === 1) return guards[0]!

  const allGuards = guards.join(', ')
  return `(ctx) => [${allGuards}].reduce((r, g) => r !== undefined && r !== true ? r : g(ctx), undefined)`
}

// ---------------------------------------------------------------------------
// Type augmentation file
// ---------------------------------------------------------------------------

/**
 * Generates the content of `auwla.gen.ts`.
 *
 * The file performs a TypeScript module augmentation on 'auwla/router',
 * declaring the discovered route paths inside the `Register` interface.
 * Once TypeScript sees this file, the following all become path-validated:
 *
 *   navigate('/posts/:id', { id: '3' })  // ✅ typed params
 *   navigate('/not-found')               // ❌ compile error
 *   isActive('/posts')                   // ✅ valid path
 *   <Link href="/unknown" />             // ❌ compile error
 *
 * The generated file must be committed to version control so that CI and
 * editor type-checking work without running the Vite dev server first.
 *
 * Example output for three pages:
 *
 *   declare module 'auwla/router' {
 *     interface Register {
 *       routes: [
 *         { path: '/' },
 *         { path: '/posts' },
 *         { path: '/posts/:id' },
 *       ]
 *     }
 *   }
 *   export {}
 */
export function generateTypeFile(pages: PageFile[]): string {
  const routeEntries = pages
    .map((p) => `      { path: ${JSON.stringify(p.routePath)} }`)
    .join(',\n')

  return [
    '// auwla.gen.ts — auto-generated by auwla/vite-router',
    '// Do not edit this file directly.',
    '//',
    '// Augments the Register interface in auwla/router to enable type-safe',
    '// navigation. Commit this file so CI type-checking works without running',
    '// the Vite dev server.',
    '',
    "declare module 'auwla/router' {",
    '  interface Register {',
    '    routes: [',
    routeEntries,
    '    ]',
    '  }',
    '}',
    '',
    '// Needed to make this a module rather than a global script.',
    'export {}',
    '',
  ].join('\n')
}
