/**
 * @fileoverview Server manifest generation for Auwla fullstack.
 *
 * Converts server module descriptors from the scanner into:
 *   - .auwla/server-manifest.js     (runtime manifest, default export)
 *   - .auwla/server-manifest.json   (runtime manifest, raw JSON)
 *   - .auwla/server-manifest.d.ts   (generated types)
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, relative } from 'node:path'
import type { ServerManifest } from '../server/types'
import type { ServerModule } from './server-scanner'

/**
 * Build the runtime manifest object from scanned server modules.
 *
 * When `rootDir` is given, module paths are stored ROOT-RELATIVE (posix
 * separators) instead of absolute (S6): the manifest is written to disk and
 * shipped to any environment that imports it, and absolute paths would leak
 * the server's directory layout. Loaders resolve them back at load time
 * (see `defaultLoad` in server/utils.ts).
 */
export function buildServerManifest(modules: ServerModule[], rootDir?: string): ServerManifest {
  const manifest: ServerManifest = {}

  for (const mod of modules) {
    for (const exp of mod.exports) {
      const key = `${mod.routeName}.${exp.name}`
      manifest[key] = {
        modulePath: rootDir ? relative(rootDir, mod.filePath).replace(/\\/g, '/') : mod.filePath,
        exportName: exp.name,
        method: exp.method,
        routePattern: mod.routePattern,
        params: mod.params,
        paramsType: mod.paramsType,
        argsType: exp.argsType,
        returnType: exp.returnType,
      }
    }
  }

  return manifest
}

/**
 * Generate the contents of .auwla/server-manifest.js.
 *
 * The module self-registers on `globalThis.__auwla_serverManifest` so the
 * adapters can resolve the manifest without statically importing the virtual
 * module (which vite import-analysis cannot resolve outside the router
 * plugin). Deliberate global state: survives double module loading when the
 * manifest and the adapter end up in separate bundles.
 */
export function generateServerManifestJs(manifest: ServerManifest): string {
  return `// Auto-generated by auwla/vite-router. Do not edit manually.
const manifest = ${JSON.stringify(manifest, null, 2)};
globalThis.__auwla_serverManifest = manifest;
export default manifest;
`
}

/**
 * Generate the contents of .auwla/server-manifest.d.ts.
 *
 * Declares both:
 *   - 'auwla:server-manifest' — runtime default export
 *   - 'auwla/server-manifest' — type augmentation for track.get/post
 */
export function generateServerManifestDts(manifest: ServerManifest): string {
  const lines: string[] = [
    '// Auto-generated by auwla/vite-router. Do not edit manually.',
    "declare module 'auwla:server-manifest' {",
    "  import type { ServerManifest } from 'auwla/server'",
    '  const manifest: ServerManifest',
    '  export default manifest',
    '}',
    '',
    "declare module 'auwla/server-manifest' {",
    '  interface ServerManifestTypes {',
  ]

  const keys = Object.keys(manifest).sort()
  for (const key of keys) {
    const entry = manifest[key]!
    const args = entry.argsType.length > 0 ? entry.argsType.join(', ') : ''
    lines.push(`    '${key}': {`)
    lines.push(`      method: '${entry.method}'`)
    lines.push(`      params: ${entry.paramsType}`)
    lines.push(`      args: [${args}]`)
    lines.push(`      return: ${entry.returnType}`)
    lines.push('    }')
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/**
 * Write the runtime manifest files to disk.
 */
export function writeServerManifest(
  outDir: string,
  manifest: ServerManifest,
): void {
  const json = JSON.stringify(manifest, null, 2)
  writeSafe(`${outDir}/server-manifest.json`, json)
  writeSafe(`${outDir}/server-manifest.js`, generateServerManifestJs(manifest))
  writeSafe(`${outDir}/server-manifest.d.ts`, generateServerManifestDts(manifest))
}

export function writeSafe(filePath: string, content: string): void {
  const dir = dirname(filePath)
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }
  writeFileSync(filePath, content, 'utf-8')
}
