// auwla.gen.ts — auto-generated by auwla/vite-router
// Do not edit this file directly.
//
// Augments the Register interface in auwla/router to enable type-safe
// navigation. Commit this file so CI type-checking works without running
// the Vite dev server.

declare module 'auwla/router' {
  interface Register {
    routes: [
      { path: "/" },
      { path: "/docs" },
      { path: "/playground" },
      { path: "/docs/:slug" }
    ]
  }
}

// Needed to make this a module rather than a global script.
export {}
