// Auto-generated by auwla-api plugin. Do not edit manually.

export type Query = Record<string, string | number>
export type Params = Record<string, string | number>

function toQuery(q?: Query): string {
  if (!q || Object.keys(q).length === 0) return ''
  const usp = new URLSearchParams(Object.entries(q).map(([k,v]) => [k, String(v)]))
  return usp.toString() ? ('?' + usp.toString()) : ''
}

function buildUrl(path: string, params?: Params, query?: Query): string {
  let p = path
  if (params) {
    for (const [k,v] of Object.entries(params)) {
      p = p.replace(':' + k, encodeURIComponent(String(v)))
    }
  }
  return '/api' + p + toQuery(query)
}

export const $api = {
  /** GET /hello */
  hello: {
    get: (args?: { params?: Params; query?: Query; body?: any }, init?: RequestInit) => {
      const url = buildUrl('/hello', args?.params, args?.query)
      return fetch(url, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
        body: args?.body ? JSON.stringify(args.body) : undefined,
        ...(init || {})
      }).then(r => r.json())
    },
  },
  /** GET /products | POST /products */
  products: {
    get: (args?: { params?: Params; query?: Query; body?: any }, init?: RequestInit) => {
      const url = buildUrl('/products', args?.params, args?.query)
      return fetch(url, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
        body: args?.body ? JSON.stringify(args.body) : undefined,
        ...(init || {})
      }).then(r => r.json())
    },
    post: (args?: { params?: Params; query?: Query; body?: any }, init?: RequestInit) => {
      const url = buildUrl('/products', args?.params, args?.query)
      return fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: args?.body ? JSON.stringify(args.body) : undefined,
        ...(init || {})
      }).then(r => r.json())
    },
  },
  /** GET /products/:id | PATCH /products/:id | DELETE /products/:id */
  product: {
    get: (args?: { params?: Params; query?: Query; body?: any }, init?: RequestInit) => {
      const url = buildUrl('/products/:id', args?.params, args?.query)
      return fetch(url, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
        body: args?.body ? JSON.stringify(args.body) : undefined,
        ...(init || {})
      }).then(r => r.json())
    },
    patch: (args?: { params?: Params; query?: Query; body?: any }, init?: RequestInit) => {
      const url = buildUrl('/products/:id', args?.params, args?.query)
      return fetch(url, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: args?.body ? JSON.stringify(args.body) : undefined,
        ...(init || {})
      }).then(r => r.json())
    },
    delete: (args?: { params?: Params; query?: Query; body?: any }, init?: RequestInit) => {
      const url = buildUrl('/products/:id', args?.params, args?.query)
      return fetch(url, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: args?.body ? JSON.stringify(args.body) : undefined,
        ...(init || {})
      }).then(r => r.json())
    },
  },
  /** GET /todos | POST /todos */
  todos: {
    get: (args?: { params?: Params; query?: Query; body?: any }, init?: RequestInit) => {
      const url = buildUrl('/todos', args?.params, args?.query)
      return fetch(url, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
        body: args?.body ? JSON.stringify(args.body) : undefined,
        ...(init || {})
      }).then(r => r.json())
    },
    post: (args?: { params?: Params; query?: Query; body?: any }, init?: RequestInit) => {
      const url = buildUrl('/todos', args?.params, args?.query)
      return fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: args?.body ? JSON.stringify(args.body) : undefined,
        ...(init || {})
      }).then(r => r.json())
    },
  },
  /** PATCH /todos/:id | DELETE /todos/:id */
  todo: {
    patch: (args?: { params?: Params; query?: Query; body?: any }, init?: RequestInit) => {
      const url = buildUrl('/todos/:id', args?.params, args?.query)
      return fetch(url, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: args?.body ? JSON.stringify(args.body) : undefined,
        ...(init || {})
      }).then(r => r.json())
    },
    delete: (args?: { params?: Params; query?: Query; body?: any }, init?: RequestInit) => {
      const url = buildUrl('/todos/:id', args?.params, args?.query)
      return fetch(url, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: args?.body ? JSON.stringify(args.body) : undefined,
        ...(init || {})
      }).then(r => r.json())
    },
  },
} as const