// Auto-generated by vite-plugin-route-types
// Do not edit manually - this file is regenerated on each build
// Generated from: src/app/routes.tsx

type AllRoutes = typeof import('./routes').allRoutes;

// Export the paths type so it can be imported and used directly
export type AppRoutePaths = '/' | '/app/devtools' | '/app/home' | '/app/perf' | '/app/route-scope-demo' | '/app/search' | '/devtools' | '/home' | '/perf' | '/route-scope-demo' | '/search' | '/simple';
export type AppRouteNames = 'devtools' | 'landing' | 'perf' | 'route-scope-demo' | 'search' | 'simple';

declare global {
  interface AuwlaRouterAppPaths {
    paths: AppRoutePaths;
    names: AppRouteNames;
  }
  
  interface AuwlaRoutePathsByName {
    'devtools': '/app/devtools';
    'landing': '/';
    'perf': '/app/perf';
    'route-scope-demo': '/app/route-scope-demo';
    'search': '/app/search';
    'simple': '/simple';
  }
}

export {}
