// Auto-generated by vite-plugin-route-types
// Do not edit manually - this file is regenerated on each build
// Generated from: src/app/routes.tsx

type AllRoutes = typeof import('./routes').allRoutes;

// Export the paths type so it can be imported and used directly
export type AppRoutePaths = '/' | '/api-test' | '/app/api-test' | '/app/devtools' | '/app/home' | '/app/perf' | '/app/route-scope-demo' | '/app/search' | '/app/todos' | '/devtools' | '/home' | '/perf' | '/portal-demo' | '/route-scope-demo' | '/search' | '/simple' | '/todos';
export type AppRouteNames = 'api-test' | 'devtools' | 'landing' | 'perf' | 'portal-demo' | 'route-scope-demo' | 'search' | 'simple' | 'todos';

declare global {
  interface AuwlaRouterAppPaths {
    paths: AppRoutePaths;
    names: AppRouteNames;
  }
  
  interface AuwlaRoutePathsByName {
    'api-test': '/app/api-test';
    'devtools': '/app/devtools';
    'landing': '/';
    'perf': '/app/perf';
    'portal-demo': '/portal-demo';
    'route-scope-demo': '/app/route-scope-demo';
    'search': '/app/search';
    'simple': '/simple';
    'todos': '/app/todos';
  }
}

export {}
