import { describe, it, expect } from 'vitest'
import { generateVirtualModule, generateTypeFile } from '../../src/vite-router/codegen'
import type { PageFile } from '../../src/vite-router/types'

// ---------------------------------------------------------------------------
// Test fixtures
// ---------------------------------------------------------------------------

/** Minimal page with only a default export. */
function makePage(routePath: string, filePath = `/src/pages${routePath === '*' ? '/[...404]' : routePath}.tsx`): PageFile {
  return {
    filePath,
    relativePath: filePath.replace('/src/pages/', ''),
    routePath,
    exports: {
      hasDefault: true,
      hasRouted:  false,
      hasPending: false,
      hasError:   false,
      hasGuard:   false,
      hasMeta:    false,
    },
  }
}

/** Page with all optional exports present. */
function makeFullPage(routePath: string, filePath = `/src/pages${routePath}.tsx`): PageFile {
  return {
    filePath,
    relativePath: filePath.replace('/src/pages/', ''),
    routePath,
    exports: {
      hasDefault: true,
      hasRouted:  true,
      hasPending: true,
      hasError:   true,
      hasGuard:   true,
      hasMeta:    true,
    },
  }
}

// ---------------------------------------------------------------------------
// generateVirtualModule
// ---------------------------------------------------------------------------

describe('generateVirtualModule', () => {
  it('emits the auwla/router import', () => {
    const code = generateVirtualModule([makePage('/')])
    expect(code).toContain("import { defineRoutes } from 'auwla/router'")
  })

  it('emits a page import for each page file', () => {
    const pages = [makePage('/'), makePage('/about')]
    const code = generateVirtualModule(pages)
    expect(code).toContain('import * as page0')
    expect(code).toContain('import * as page1')
  })

  it('wraps the route array in defineRoutes()', () => {
    const code = generateVirtualModule([makePage('/')])
    expect(code).toContain('export default defineRoutes([')
  })

  it('emits correct path for each route', () => {
    const pages = [makePage('/'), makePage('/posts'), makePage('/posts/:id')]
    const code = generateVirtualModule(pages)
    expect(code).toContain('"/"')
    expect(code).toContain('"/posts"')
    expect(code).toContain('"/posts/:id"')
  })

  it('emits component property using the page alias', () => {
    const code = generateVirtualModule([makePage('/')])
    expect(code).toContain('component: page0.default')
  })

  it('omits optional properties when not exported', () => {
    const code = generateVirtualModule([makePage('/')])
    expect(code).not.toContain('routed')
    expect(code).not.toContain('pendingComponent')
    expect(code).not.toContain('errorComponent')
    expect(code).not.toContain('guard')
    expect(code).not.toContain('meta')
  })

  it('emits all optional properties when all exports are present', () => {
    const code = generateVirtualModule([makeFullPage('/posts/:id')])
    expect(code).toContain('routed: page0.routed')
    expect(code).toContain('pendingComponent: page0.pending')
    expect(code).toContain('errorComponent: page0.error')
    expect(code).toContain('guard: page0.guard')
    expect(code).toContain('meta: page0.meta')
  })

  it('normalises Windows backslashes in import paths', () => {
    const page: PageFile = {
      ...makePage('/posts'),
      filePath: 'C:\\src\\pages\\posts\\index.tsx',
    }
    const code = generateVirtualModule([page])
    expect(code).toContain('C:/src/pages/posts/index.tsx')
    expect(code).not.toContain('\\')
  })

  it('produces valid JS for an empty pages list', () => {
    const code = generateVirtualModule([])
    // The generator always emits the closing bracket on its own line.
    expect(code).toContain('export default defineRoutes([')
    expect(code).toContain('])')
  })

  it('includes the do-not-edit header comment', () => {
    const code = generateVirtualModule([])
    expect(code).toContain('auto-generated by auwla/vite-router')
  })

  it('uses page index as a stable alias (page0, page1, …)', () => {
    const pages = [makePage('/a'), makePage('/b'), makePage('/c')]
    const code = generateVirtualModule(pages)
    expect(code).toContain('page0.default')
    expect(code).toContain('page1.default')
    expect(code).toContain('page2.default')
  })
})

// ---------------------------------------------------------------------------
// generateTypeFile
// ---------------------------------------------------------------------------

describe('generateTypeFile', () => {
  it('augments the auwla/router module', () => {
    const code = generateTypeFile([makePage('/')])
    expect(code).toContain("declare module 'auwla/router'")
  })

  it('declares the Register interface', () => {
    const code = generateTypeFile([makePage('/')])
    expect(code).toContain('interface Register')
  })

  it('includes each discovered route path', () => {
    const pages = [makePage('/'), makePage('/posts'), makePage('/posts/:id')]
    const code = generateTypeFile(pages)
    expect(code).toContain('"/"')
    expect(code).toContain('"/posts"')
    expect(code).toContain('"/posts/:id"')
  })

  it('includes the catch-all route when present', () => {
    const code = generateTypeFile([makePage('*')])
    expect(code).toContain('"*"')
  })

  it('ends with `export {}` to make it a module', () => {
    const code = generateTypeFile([])
    expect(code).toContain('export {}')
  })

  it('includes the do-not-edit header comment', () => {
    const code = generateTypeFile([])
    expect(code).toContain('auto-generated by auwla/vite-router')
  })

  it('produces a valid empty declaration for zero pages', () => {
    const code = generateTypeFile([])
    // Should still be syntactically complete even with no routes
    expect(code).toContain('interface Register')
    expect(code).toContain('export {}')
  })

  it('does not include file paths — only route paths', () => {
    const page = makeFullPage('/posts/:id', '/absolute/path/to/posts/[id].tsx')
    const code = generateTypeFile([page])
    expect(code).not.toContain('/absolute/path')
    expect(code).not.toContain('[id]')
  })
})
